### ISSUE TITLE
Add BNO055 sensor to the shield

### ISSUE THREAD

**Issue by Sokario** [catie-aq/zephyr_zest-sensor-imu#3]

**Comment by Sokario** [comment]
I added BNO055 sensor to the DT.
However I was wondering how to made optional I2C address available without the need to change `app.overlay`

@bperraudin I propose the following:
- The shield is designed to be used either with BNO055 on `0x28` or `0x29` I2C address.
- The shield is also designed for the BNO055 to use an Xtal.
As the shield is designed on either I2C address and use the Xtal, the DT should propose each configuration WITH the Xtal used.

To do so I defined to BNO055 in the DT each one on a different I2C address [here](https://github.com/catie-aq/zephyr_zest-sensor-imu/blob/bbf66bf1ab4fc6cf34dc661e87e9326363fb4ddc/boards/shields/zest-sensor-imu/zest_sensor_imu.overlay#L23-L27) and [here](https://github.com/catie-aq/zephyr_zest-sensor-imu/blob/bbf66bf1ab4fc6cf34dc661e87e9326363fb4ddc/boards/shields/zest-sensor-imu/zest_sensor_imu.overlay#L29-L33).
Each one got the property `use_xtal = <1>`
Aliases are created [here](https://github.com/catie-aq/zephyr_zest-sensor-imu/blob/bbf66bf1ab4fc6cf34dc661e87e9326363fb4ddc/boards/shields/zest-sensor-imu/zest_sensor_imu.overlay#L10-L11) to allow the use of :
> static const struct device *bno = DEVICE_DT_GET(DT_ALIAS(bno055));
or
static const struct device *bno = DEVICE_DT_GET(DT_ALIAS(bno055_alt));

If the user remove the Xtal, i.e do not want to use the shield for the designed use case. He would have to change `use_xtal` property in the `app.overlay`.

@bperraudin What do you think of this proposition ?

**Comment by bperraudin** [comment]
@Sokario I think we should "just" implement the default configuration.

It would be the responsibility of the end user to change the address if necessary.
